# Generated by Django 3.0.14 on 2022-01-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
